config/routes.rb
Rails.application.routes.draw do
  resources :foos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foo.rb
class Foo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foos_controller.rb
class FoosController < ApplicationController
  before_action :set_foo, only: %i[ show edit update destroy ]

  # GET /foos or /foos.json
  def index
    @foos = Foo.all
  end

  # GET /foos/1 or /foos/1.json
  def show
  end

  # GET /foos/new
  def new
    @foo = Foo.new
  end

  # GET /foos/1/edit
  def edit
  end

  # POST /foos or /foos.json
  def create
    @foo = Foo.new(foo_params)

    respond_to do |format|
      if @foo.save
        format.html { redirect_to foo_url(@foo), notice: "Foo was successfully created." }
        format.json { render :show, status: :created, location: @foo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foos/1 or /foos/1.json
  def update
    respond_to do |format|
      if @foo.update(foo_params)
        format.html { redirect_to foo_url(@foo), notice: "Foo was successfully updated." }
        format.json { render :show, status: :ok, location: @foo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foos/1 or /foos/1.json
  def destroy
    @foo.destroy

    respond_to do |format|
      format.html { redirect_to foos_url, notice: "Foo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foo
      @foo = Foo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foo_params
      params.require(:foo).permit(:bar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foos_helper.rb
module FoosHelper
end

app/views/foos/_form.html.erb
<%= form_with(model: foo) do |form| %>
  <% if foo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foo.errors.count, "error") %> prohibited this foo from being saved:</h2>

      <ul>
        <% foo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bar %>
    <%= form.text_field :bar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foos/_pagy.html.slim
br
= request.path
br
= request.url
br
= request.inspect

app/views/foos/edit.html.erb
<h1>Editing Foo</h1>

<%= render 'form', foo: @foo %>

<%= link_to 'Show', @foo %> |
<%= link_to 'Back', foos_path %>

app/views/foos/index.html.slim
p#notice
  = notice
h1
  | Foos
table
  thead
    tr
      th
        | Bar
      th[colspan="3"]
  tbody
    - @foos.each do |foo|
      tr
        td
          = foo.bar
        td
          = link_to 'Show', foo
        td
          = link_to 'Edit', edit_foo_path(foo)
        td
          = link_to 'Destroy', foo, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Foo', new_foo_path
br
= button_tag('click me', data: { reflex: 'click->Example#count'})
br
= request.path
br
= request.url
br
= request.inspect
#selector
  = render(partial: 'foos/pagy')

app/views/foos/new.html.erb
<h1>New Foo</h1>

<%= render 'form', foo: @foo %>

<%= link_to 'Back', foos_path %>

app/views/foos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bar:</strong>
  <%= @foo.bar %>
</p>

<%= link_to 'Edit', edit_foo_path(@foo) %> |
<%= link_to 'Back', foos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>